name: 🧪 Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: 🏗️ Build Test
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🏗️ Build Site
        uses: ./.github/actions/build
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
